name: digital_scientist
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  confetti: ^0.7.0
  flick_video_player: ^0.8.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_staggered_animations: ^1.1.1
  flutter_tts: ^4.0.2
  google_mobile_ads: ^5.0.0

  image_picker: ^1.1.1
  lottie: ^3.1.0
  provider: ^6.1.2
  video_player: ^2.8.6
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/icons/
   - assets/lottie/
   - assets/videos/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf
    - family: Jost
      fonts:
        - asset: assets/fonts/jost.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto.ttf
